In [1]:
import numpy as np

# 일차원 array

In [3]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])
a

array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])

## 중복된 값 제거하기

In [5]:
unique_values = np.unique(a)
unique_values

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

## 중복된 값 제거하고, 처음 등장하는 값의 인덱스 반환하기

In [9]:
unique_values, indices_list = np.unique(a, return_index = True) # return_index=False, axis=False가 기본값
print(indices_list)

[ 0  2  3  4  5  6  7 12 13 14]


## 중복된 값 제거하고, 해당 값이 몇개 존재하는지 반환하기

In [11]:
unique_values, occurrence_count = np.unique(a, return_counts = True)
print(occurrence_count)

[3 2 2 2 1 1 1 1 1 1]


# 2차원 array

In [13]:
a_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [1, 2, 3, 4]])
a_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4]])

In [17]:
unique_values = np.unique(a_2d) # 1차원 형태로 반환됨
unique_values

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [18]:
unique_rows = np.unique(a_2d, axis=0)
unique_rows

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [19]:
unique_columns = np.unique(a_2d, axis=1)
unique_columns

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4]])

In [20]:
unique_rows, unique_indices, unique_counts = np.unique(a_2d, axis=0, return_index=True, return_counts=True)
print(unique_indices)
print(unique_counts)

[0 1 2]
[2 1 1]


* 2차원 배열에서 return_index 추가 설명 : 3번째 행은 중복이기 때문에, 중복을 제거하고 유니크한 행이 0, 1, 2번째 행이 됨.
* 2차원 배열에서 return_counts 추가 설명 : 유니크한 행에 대한 빈도를 보면 0번 행이 중복되어 2회, 1, 2번 행은 중복되지 않아서 1회.
<br/>
* 축 기준 자체로 두고 보기. 하나하나의 원소로 보는 것이 아니다!!