In [1]:
import numpy as np

In [3]:
data = np.arange(1, 7)
data

array([1, 2, 3, 4, 5, 6])

In [4]:
data.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
data.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [6]:
arr = np.arange(6).reshape((2, 3))
arr

array([[0, 1, 2],
       [3, 4, 5]])

# 전치행렬 :  aT*a | 전치행렬과 원래 행렬을 곱할 때 사용 ex. 내적
* arr.T
* arr.transpose()

In [7]:
arr.transpose()

array([[0, 3],
       [1, 4],
       [2, 5]])

In [9]:
arr.T

array([[0, 3],
       [1, 4],
       [2, 5]])

# 역순정렬
* np.flip(arr)
* arr[::-1]

In [11]:
arr = np.arange(1,9)
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [12]:
np.flip(arr)

array([8, 7, 6, 5, 4, 3, 2, 1])

In [13]:
arr[::-1]

array([8, 7, 6, 5, 4, 3, 2, 1])

In [14]:
arr_2d = np.arange(1,13).reshape(3, 4)
arr_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [15]:
np.flip(arr_2d)

array([[12, 11, 10,  9],
       [ 8,  7,  6,  5],
       [ 4,  3,  2,  1]])

In [17]:
np.flip(arr_2d, axis=0)

array([[ 9, 10, 11, 12],
       [ 5,  6,  7,  8],
       [ 1,  2,  3,  4]])

In [20]:
arr_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [21]:
np.flip(arr_2d, axis=1)

array([[ 4,  3,  2,  1],
       [ 8,  7,  6,  5],
       [12, 11, 10,  9]])

In [25]:
arr_2d[1] = np.flip(arr_2d[1])
arr_2d

array([[ 1,  2,  3,  4],
       [ 8,  7,  6,  5],
       [ 9, 10, 11, 12]])

In [26]:
arr_2d[:, 1] = np.flip(arr_2d[:, 1])
arr_2d

array([[ 1, 10,  3,  4],
       [ 8,  7,  6,  5],
       [ 9,  2, 11, 12]])