In [1]:
import numpy as np

# flatten() : 얕은 복사. 원본 변화 없음. 사본 만듦.
# ravel() : 깊은 복사. 원본 변화 있음. 사본 안 만듦.

In [4]:
x = np.arange(1, 13).reshape(3, 4)
x

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [5]:
x.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [7]:
a1 = x.flatten()
a1[0] = 99
x # 변하지 않음

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [8]:
a2 = x.ravel()
a2[0] = 99
x # 변함

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

* 딥러닝에서 자주 사용되는 method이다. 잘 알아두기.