# MSE (Mean Square Error)
* 회귀 (regression) 문제를 풀 때, 예측한 값과 실제 측정 값 사이의 오차를 구할 때 사용
![meansquareerror](https://numpy.org/doc/stable/_images/np_MSE_formula.png)
* (실제값 - 예측값)^2의 평균

In [1]:
import numpy as np

In [3]:
predictions = np.ones(3, dtype=int)
predictions

array([1, 1, 1])

In [4]:
labels = np.arange(1, 4)
labels

array([1, 2, 3])

In [5]:
predictions - labels

array([ 0, -1, -2])

In [6]:
np.square(predictions - labels)

array([0, 1, 4], dtype=int32)

In [7]:
np.sum(np.square(predictions - labels))

5

In [9]:
mse = np.sum(np.square(predictions - labels)) * (1/3)
mse

1.6666666666666665

# RMSE (Root Mean Squared Error)

In [14]:
rmse = np.sqrt(mse)
rmse

1.2909944487358056

# MAE (Mean Absolute Error)
* 예측값과 실제값의 차이에 대한 절대값의 평균

In [16]:
error = predictions - labels
error

array([ 0, -1, -2])

In [17]:
np.abs(error)

array([0, 1, 2])

In [19]:
mae = np.mean(np.abs(error))
mae

1.0

# MAPE (Mean Absolute Percentage Error)
* (실제값 - 예측값) / 실제값의 절대값에 대한 평균

In [20]:
(predictions - labels) / labels

array([ 0.        , -0.5       , -0.66666667])

In [21]:
np.abs((predictions - labels) / labels)

array([0.        , 0.5       , 0.66666667])

In [23]:
mape = np.mean(np.abs((predictions - labels) / labels))
mape

0.38888888888888884

* 위의 값들은 작을 수록 정확도가 높음을 의미한다.