In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [3]:
np.save('filename', a)

In [4]:
np.load('filename.npy')

array([1, 2, 3, 4, 5, 6])

In [5]:
b = np.load('filename.npy')
b

array([1, 2, 3, 4, 5, 6])

In [6]:
csv_arr = np.array([1,2,3,4,5,6,7,8])
csv_arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [7]:
np.savetxt('new_file.csv', csv_arr)

In [8]:
np.loadtxt('new_file.csv')

array([1., 2., 3., 4., 5., 6., 7., 8.])

# Pandas를 활용한 파일 저장 (추천하는 방식)
    a = np.array([1, 2, 3, '4', 5, 6])
* 배열의 한 요소만 문자이더라도 결국에는 배열의 모든 원소가 문자로 바뀜 (하나의 동일한 데이터 타입만 취급한다.)
* np.savetxt의 경우, 에러가 발생함 (문자를 저장할 수 없음)

In [10]:
import pandas as pd

In [13]:
music = [['Billie Holiday', 'Jazz', 1300000, 27000000], 
         ['Jimmie Hendrix', 'Rock', 2700000, 70000000],
         ['Miles Davis', 'Jazz', 1500000, 48000000],
         ['SIA', 'Pop', 2000000, 74000000]]
music

[['Billie Holiday', 'Jazz', 1300000, 27000000],
 ['Jimmie Hendrix', 'Rock', 2700000, 70000000],
 ['Miles Davis', 'Jazz', 1500000, 48000000],
 ['SIA', 'Pop', 2000000, 74000000]]

In [14]:
pd.DataFrame(music)

0     1        2         3
0  Billie Holiday  Jazz  1300000  27000000
1  Jimmie Hendrix  Rock  2700000  70000000
2     Miles Davis  Jazz  1500000  48000000
3             SIA   Pop  2000000  74000000

In [16]:
df = pd.DataFrame(music)
df

0     1        2         3
0  Billie Holiday  Jazz  1300000  27000000
1  Jimmie Hendrix  Rock  2700000  70000000
2     Miles Davis  Jazz  1500000  48000000
3             SIA   Pop  2000000  74000000

In [21]:
df.to_csv('music.csv', index=False)

In [22]:
pd.read_csv('music.csv')

0     1        2         3
0  Billie Holiday  Jazz  1300000  27000000
1  Jimmie Hendrix  Rock  2700000  70000000
2     Miles Davis  Jazz  1500000  48000000
3             SIA   Pop  2000000  74000000

In [23]:
a = np.array([[-2.58289208,  0.43014843, -1.24082018, 1.59572603],
              [ 0.99027828, 1.17150989,  0.94125714, -0.14692469],
              [ 0.76989341,  0.81299683, -0.95068423, 0.11769564],
              [ 0.20484034,  0.34784527,  1.96979195, 0.51992837]])
a

array([[-2.58289208,  0.43014843, -1.24082018,  1.59572603],
       [ 0.99027828,  1.17150989,  0.94125714, -0.14692469],
       [ 0.76989341,  0.81299683, -0.95068423,  0.11769564],
       [ 0.20484034,  0.34784527,  1.96979195,  0.51992837]])

In [28]:
df = pd.DataFrame(a)
print(df)

          0         1         2         3
0 -2.582892  0.430148 -1.240820  1.595726
1  0.990278  1.171510  0.941257 -0.146925
2  0.769893  0.812997 -0.950684  0.117696
3  0.204840  0.347845  1.969792  0.519928


In [31]:
df.to_csv('pd.csv', index=False)

In [32]:
pd.read_csv('pd.csv')

0         1         2         3
0 -2.582892  0.430148 -1.240820  1.595726
1  0.990278  1.171510  0.941257 -0.146925
2  0.769893  0.812997 -0.950684  0.117696
3  0.204840  0.347845  1.969792  0.519928