In [1]:
import numpy as np

In [3]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [4]:
np.newaxis

In [5]:
# 축 늘어나게
a2 = a[np.newaxis, :]
a2

array([[0, 1, 2, 3, 4, 5]])

In [8]:
print(a.shape)
print(a2.shape)
a.shape, a2.shape

(6,)
(1, 6)


((6,), (1, 6))

## Python 리스트 vs. Numpy 배열
* Python 리스트 : 단일 목록 내에 다양한 데이터 유형을 포함할 수 있음
* Numpy 배열 : 모든 요소는 동종이어야 한다. 배열에 대해 수행되는 수학 연산은 배열이 동종이 아닌 경우 매우 비효율적임

In [10]:
a_list = [0, "1", 2.0, 3]
type(a_list)

list

In [11]:
np.array(a_list)

array(['0', '1', '2.0', '3'], dtype='<U32')

## 그럼에도 numpy를 사용하는 이유
* Numpy 배열은 Python 리스트보다 빠르고 컴팩트하다.
* 배열은 메모리를 덜 소모하고 사용하기 편리하다.
* Numpy는 데이터를 저장하는 데 훨씬 적은 메모리를 사용한다.

In [13]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [15]:
b = np.array([[1,1,1,1,1],[2,2,2,2,2],[3,3,3,3,3]])
b

array([[1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3]])

## numpy 배열 만들기

In [17]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [18]:
a = np.zeros(2)
a

array([0., 0.])

In [20]:
a = np.zeros([2,3])
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [21]:
a = np.ones(2)
a

array([1., 1.])

In [22]:
a = np.ones([3,4])
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [24]:
np.empty(10) # 초기화를 진행하지 않기 때문에 속도가 더 빠르다

array([ 6.79038654e-313,  6.79038653e-313,  2.37663529e-312,
        2.14321575e-312,  2.37663529e-312,  2.56761491e-312,
        1.06099790e-312,  2.12199579e-313, -1.57234176e-063,
        0.00000000e+000])

In [26]:
np.empty([5,2])

array([[ 6.79038654e-313,  6.79038653e-313],
       [ 2.37663529e-312,  2.14321575e-312],
       [ 2.37663529e-312,  2.56761491e-312],
       [ 1.06099790e-312,  2.12199579e-313],
       [-1.57234176e-063,  0.00000000e+000]])

In [25]:
np.arange(10) # 파이썬에서 range 함수와 동일

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
np.linspace(0, 10, num=5) # 지정 범위의 균일한 간격의 숫자 반환

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [28]:
np.linspace(0,10,num=10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [29]:
np.ones(2, dtype=np.int64)

array([1, 1], dtype=int64)

In [31]:
np.ones([2,4], dtype=np.int64)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int64)

## 배열 생성 속도 측정

In [41]:
%timeit np.zeros(1000000000)

51.8 µs ± 1.81 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [42]:
%timeit np.empty(1000000000)

55.2 µs ± 5.35 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)
