## 정렬
* 기본값 axis=-1 : 마지막 차원을 기본값으로 정렬
* np.sort()
* np.argsort() : 지정된 축으로 정렬할 인덱스 순서 반환
* np.lexsort() : 키값으로 정렬
* np.searchsorted() : 정렬된 배열에서 요소 찾기
* np.partition() : 부분정렬

In [3]:
import numpy as np

In [4]:
arr = np.array([2,1,5,3,7,4,6,8])
arr

array([2, 1, 5, 3, 7, 4, 6, 8])

### 정렬

In [5]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

### 역순 정렬

In [6]:
np.sort(arr)[::-1]

array([8, 7, 6, 5, 4, 3, 2, 1])

### 3 x 4 2차원 배열 만들기 (random)

In [10]:
np.random.seed(42)
a = np.random.randint(0,10,12).reshape([3,4])
a

array([[6, 3, 7, 4],
       [6, 9, 2, 6],
       [7, 4, 3, 7]])

In [11]:
a.shape

(3, 4)

### 2차원 배열 정렬하기

In [13]:
np.sort(a) # axis=-1이므로 4를 기준으로 정렬한다.

array([[3, 4, 6, 7],
       [2, 6, 6, 9],
       [3, 4, 7, 7]])

### 2차원 배열 역순 정렬하기

In [14]:
np.sort(a)[:, ::-1]

array([[7, 6, 4, 3],
       [9, 6, 6, 2],
       [7, 7, 4, 3]])

### 2차원 배열 열 기준으로 정렬하기

In [15]:
np.sort(a, axis=0)

array([[6, 3, 2, 4],
       [6, 4, 3, 6],
       [7, 9, 7, 7]])

### 2차원 배열 열 기준으로 역순 정렬하기

In [18]:
np.sort(a, axis=0)[::-1, :]

array([[7, 9, 7, 7],
       [6, 4, 3, 6],
       [6, 3, 2, 4]])

In [19]:
np.random.seed(42)
a = np.random.randint(0,10,12).reshape([3,4])
a

array([[6, 3, 7, 4],
       [6, 9, 2, 6],
       [7, 4, 3, 7]])

### 2차원 배열의 가장 큰 값의 인덱스 반환하기

In [20]:
np.argsort(a) # 인덱스 값 반환

array([[1, 3, 0, 2],
       [2, 0, 3, 1],
       [2, 1, 0, 3]], dtype=int64)

In [21]:
np.argsort(a, axis=0)[::-1, :]

array([[2, 1, 0, 2],
       [1, 2, 2, 1],
       [0, 0, 1, 0]], dtype=int64)

## concatenate

In [29]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [30]:
np.concatenate([a, b])

array([1, 2, 3, 4, 5, 6, 7, 8])

In [31]:
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

### 2차원 배열 합치기

In [32]:
x = np.array([[1,2], [3,4]])
y = np.array([[5,6]])
x.shape, y.shape

((2, 2), (1, 2))

In [33]:
np.concatenate((x,y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])