In [2]:
import numpy as np

In [3]:
array_example = np.array ([[[0,1,2,3], [4,5,6,7]],
                          [[0,1,2,3], [4,5,6,7]],
                          [[0,1,2,3], [4,5,6,7]]])
array_example

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

### ndim : 배열의 차원을 알려주는 함수

In [4]:
array_example.ndim

3

### size : 배열의 element 개수를 알려주는 함수

In [6]:
array_example.size

24

### shape : 배열의 형태를 알려주는 함수

In [8]:
array_example.shape

(3, 2, 4)

### reshape : 배열을 재배열해주는 함수

In [10]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [11]:
a.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [12]:
a.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [14]:
a
# 값이 아예 바뀌는 것이 아니라 사본이 바뀌는 것

array([0, 1, 2, 3, 4, 5])