In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4,5,6])

In [3]:
a

array([1, 2, 3, 4, 5, 6])

In [4]:
a.shape

(6,)

### newaxis : numpy 배열의 차원을 늘려주는 함수

#### 행 (Row) 확장

In [5]:
a2 = a[np.newaxis, :]
a2

array([[1, 2, 3, 4, 5, 6]])

In [6]:
a2.shape

(1, 6)

#### 열 (Column) 확장

In [7]:
a22 = a[:, np.newaxis]
a22

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [8]:
a22.shape

(6, 1)

### expand_dims : numpy 배열의 차원을 확장해주는 함수

In [9]:
b = np.expand_dims(a, axis=1)
b

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [10]:
b.shape

(6, 1)

In [11]:
c = np.expand_dims(a, axis=0)
c

array([[1, 2, 3, 4, 5, 6]])

In [12]:
c.shape

(1, 6)

### indexing

In [13]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [14]:
a < 5

array([[ True,  True,  True,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [15]:
a[a<5]

array([1, 2, 3, 4])

In [16]:
a[a>5]

array([ 6,  7,  8,  9, 10, 11, 12])

In [18]:
even = a[a%2 == 0]
even

array([ 2,  4,  6,  8, 10, 12])

In [21]:
even_better = a[(a%2 == 0) & (a<5)]
even_better

array([2, 4])

#### nonzero : 요소들 중에서 조건에 해당하는 값의 index를 알려주는 함수

In [26]:
arr = np.array([[1, 0, 7], [8, 1, 0], [1, 0, 0]])
arr

array([[1, 0, 7],
       [8, 1, 0],
       [1, 0, 0]])

In [28]:
np.nonzero(arr<7)

(array([0, 0, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 1, 1, 2, 0, 1, 2], dtype=int64))

#### tuple 형태로 표현하기

In [30]:
list_of_coordinates = list(zip(b[0], b[1]))
for coord in list_of_coordinates:
    print(coord)

(1, 2)
