In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4,5,6,7,8,9,10])
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
arr1 = a[3:8]
arr1

array([4, 5, 6, 7, 8])

In [4]:
a1 = np.array([[1, 1], [2, 2]])
a2 = np.array([[3, 3], [3, 3]])
a1, a2

(array([[1, 1],
        [2, 2]]),
 array([[3, 3],
        [3, 3]]))

# vertical 하게 합치기 : vstack
* 열 개수가 같아야 한다.
* 행 개수는 상관 없다.

In [5]:
np.vstack((a1, a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [3, 3]])

# horizontal 하게 합치기 : hstack
* 행 개수가 같아야 한다.
* 열 개수는 상관 없다.

In [7]:
np.hstack((a1, a2))

array([[1, 1, 3, 3],
       [2, 2, 3, 3]])

# 행으로 데이터 나누기 : hsplit
* np.hsplit(x, n)
* np.split(x, n, axis=1)

![hsplit_vsplit](https://t1.daumcdn.net/cfile/tistory/99A00D375B039E8316)

In [26]:
x = np.arange(0,18).reshape(3,6)
x

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

In [27]:
np.hsplit(x, 3)

[array([[ 0,  1],
        [ 6,  7],
        [12, 13]]),
 array([[ 2,  3],
        [ 8,  9],
        [14, 15]]),
 array([[ 4,  5],
        [10, 11],
        [16, 17]])]

# 열로 데이터 나누기 : vsplit
* np.vsplit(x, n)
* np.split(x, n, axis=0)

In [28]:
np.vsplit(x, 3)

[array([[0, 1, 2, 3, 4, 5]]),
 array([[ 6,  7,  8,  9, 10, 11]]),
 array([[12, 13, 14, 15, 16, 17]])]

# 튜플로 데이터 나누기
* 인덱스 값을 기준으로해서 그 인덱스 사이의 값과 그 전 부분, 그 후 부분으로 나뉜다.

In [31]:
x.reshape(2,9)
x

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

In [32]:
np.hsplit(x, (2,5))

[array([[ 0,  1],
        [ 6,  7],
        [12, 13]]),
 array([[ 2,  3,  4],
        [ 8,  9, 10],
        [14, 15, 16]]),
 array([[ 5],
        [11],
        [17]])]

In [34]:
x.reshape(6,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [35]:
np.vsplit(x, (1,4))

[array([[0, 1, 2, 3, 4, 5]]),
 array([[ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17]]),
 array([], shape=(0, 6), dtype=int32)]

# 얕은 복사와 깊은 복사
* shallow copy
* deep copy

## 얕은 복사

In [38]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [40]:
b1 = a[0, :]
b1

array([1, 2, 3, 4])

In [41]:
b1[0] = 99
b1

array([99,  2,  3,  4])

In [42]:
a
# a의 a[0][0] 값도 바뀐 것을 볼 수 있다.

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

## 깊은 복사

In [44]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [51]:
b2 = a[0, :].copy()
b2

array([1, 2, 3, 4])

In [52]:
b2[0] = 99
b2

array([99,  2,  3,  4])

In [53]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])