In [2]:
import numpy as np

# 사칙연산

In [5]:
data = np.array([1,2])
ones = np.ones(2, dtype=int)

data, ones

(array([1, 2]), array([1, 1]))

In [6]:
data + ones

array([2, 3])

In [7]:
data - ones

array([0, 1])

In [8]:
data * data

array([1, 4])

In [9]:
data / data

array([1., 1.])

# np.array의 합을 구하는 함수 : sum()

In [10]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [11]:
a.sum()

10

In [17]:
b = np.array([[1,1], [2,2], [3,3]])
b

array([[1, 1],
       [2, 2],
       [3, 3]])

In [18]:
b.sum()

12

In [19]:
b.sum(axis=0)

array([6, 6])

In [20]:
b.sum(axis=1)

array([2, 4, 6])

### axis=0과 axis=1
* axis = 0 : 각 열의 모든 행에 대해서 동작한다. (이차원 배열에서 앞쪽 (0번) 인덱스가 바뀐다.)
* axis = 1 : 각 행의 모든 열에 대해서 동작한다. (이차원 배열에서 뒷쪽 (1번) 인덱스가 바뀐다.)

    b.sum(axis=0) = [ b[0][0] + b[1][0] + b[2][0], b[0][1] + b[1][1] + b[2][1] ]<br/>
    b.sum(axis=1) = [ b[0][0] + b[0][1], b[1][0] + b[1][1], b[2][0] + b[2][1] ]