<h1>Broadcasting (브로드캐스팅)</h1>
* 배열과 scala 값을 연산하든가, 배열의 크기가 서로 다른 두 배열을 연산하는 과정에서 사용할 수 있는 방식.

In [2]:
import numpy as np

In [3]:
data = np.array([1.0, 2.0])
data * 1.6

array([1.6, 3.2])

In [4]:
a = np.array([1.0, 2.0, 3.0])
b = np.array([2.0, 2.0, 2.0])
a + b

array([3., 4., 5.])

In [5]:
a - b

array([-1.,  0.,  1.])

In [6]:
a * b

array([2., 4., 6.])

In [7]:
a / b

array([0.5, 1. , 1.5])

In [15]:
a = np.array([[0.0, 0.0, 0.0],
          [10.0, 10.0, 10.0],
          [20.0, 20.0, 10.0],
          [30.0, 30.0, 30.0]])
b = np.array([1.0, 2.0, 3.0])
a + b

array([[ 1.,  2.,  3.],
       [11., 12., 13.],
       [21., 22., 13.],
       [31., 32., 33.]])

In [17]:
a.shape, b.shape

((4, 3), (3,))

In [26]:
a = np.array([0.0, 10.0, 20.0, 30.0])
b = np.array([1.0, 2.0, 3.0])
a.shape, b.shape
# a + b : 에러 발생

((4,), (3,))

In [31]:
a1 = a[:, np.newaxis]
print(a1, a1.shape)

[[ 0.]
 [10.]
 [20.]
 [30.]] (4, 1)


In [32]:
a2 = a[np.newaxis, :]
print(a2, a2.shape)

[[ 0. 10. 20. 30.]] (1, 4)


In [29]:
a1 + b

array([[ 1.,  2.,  3.],
       [11., 12., 13.],
       [21., 22., 23.],
       [31., 32., 33.]])

In [33]:
b1 = b[:, np.newaxis]

In [34]:
a + b1

array([[ 1., 11., 21., 31.],
       [ 2., 12., 22., 32.],
       [ 3., 13., 23., 33.]])