In [1]:
import numpy as np

In [2]:
data = np.array([1,2,3])
data

array([1, 2, 3])

In [4]:
data.max()

3

In [5]:
data.min()

1

In [6]:
data.sum()

6

In [7]:
data.mean()

2.0

In [8]:
data.prod()

6

In [9]:
data.std() # 표준편차

0.816496580927726

In [10]:
data.var() # 분산

0.6666666666666666

In [12]:
a = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])
a

array([[0.45053314, 0.17296777, 0.34376245, 0.5510652 ],
       [0.54627315, 0.05093587, 0.40067661, 0.55645993],
       [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

In [13]:
a.shape

(3, 4)

In [14]:
a.sum()

4.8595784

In [15]:
a.min()

0.05093587

In [16]:
a.min(axis=0)

array([0.12697628, 0.05093587, 0.26590556, 0.5510652 ])

In [17]:
a.min(axis=1)

array([0.17296777, 0.05093587, 0.12697628])

In [19]:
data = np.array([[1, 2], [3, 4], [5, 6]])
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [20]:
data.ndim

2

In [21]:
data.shape

(3, 2)

In [22]:
data[0, 1]

2

In [23]:
data[0]

array([1, 2])

In [24]:
data[1:3]

array([[3, 4],
       [5, 6]])

In [25]:
data[0:2, 0]

array([1, 3])

+ 3차원 배열 : 맨 앞에 있는 축이 가장 늦게 생성되고, 맨 뒤에 있는 축이 가장 빠르게 생성된다.

In [26]:
np.ones((4,3,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])